# Generated by Django 5.2.15 on 2026-07-04 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creem_customer_id', models.CharField(blank=True, max_length=100)),
                ('creem_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.org')),
            ],
        ),
    ]
