# Generated by Django 5.2.15 on 2026-07-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(blank=True, max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('commit', models.CharField(blank=True, max_length=64)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_events', models.TextField()),
                ('parsed', models.JSONField()),
                ('hosts_total', models.PositiveIntegerField(default=0)),
                ('hosts_changed', models.PositiveIntegerField(default=0)),
                ('tasks_changed', models.PositiveIntegerField(default=0)),
                ('not_previewed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
